defmodule Cqr.Populate.Entities do
  @moduledoc false

  # Static entity definitions for the cognitive-test population task.
  # Each entry is {namespace, name, type, description, derived_from_list}.
  # All descriptions are pure ASCII so they round-trip through the MCP
  # wire format without tripping JSON parsers on non-ASCII glyphs.

  @bootstrap ["entity:project:bootstrap"]

  def all do
    Enum.flat_map(sections(), fn {_label, entries} -> entries end)
  end

  def sections do
    [
      {"CQR Protocol Primitives", primitives()},
      {"Architecture Components", architecture()},
      {"Technology Stack", tech()},
      {"Bug Log", bugs()},
      {"Strategic Positioning", strategy()},
      {"Business Metrics", metrics()},
      {"Cross-Domain Insights", insights()},
      {"V2 Roadmap", roadmap()},
      {"Governance Concepts", governance()},
      {"Lessons Learned", lessons()},
      {"Organizational Context", org()},
      {"Cognitive Test Scenarios", scenarios()}
    ]
  end

  defp primitives do
    [
      {"cqr", "resolve", "definition",
       "Deterministic lookup primitive. Maps to recognition: retrieve a known entity by identity within the agents visible scope.",
       @bootstrap},
      {"cqr", "discover", "definition",
       "Multi-paradigm search primitive. Maps to exploration: BM25 text plus vector similarity plus graph traversal under scope isolation.",
       @bootstrap},
      {"cqr", "assert", "definition",
       "Write primitive. Maps to claim making: creates a new entity with derivation provenance and confidence inside a target scope.",
       @bootstrap},
      {"cqr", "certify", "definition",
       "Governance primitive. Maps to consecration: an authority elevates an asserted entity to certified status with an audit trail.",
       @bootstrap},
      {"cqr", "trace", "definition",
       "Provenance primitive. Maps to audit: returns the full lifecycle of an entity including asserts, certs, signals and derivations.",
       @bootstrap},
      {"cqr", "signal", "definition",
       "Quality feedback primitive. Maps to reputation update: adjusts an entitys reputation with a reason and preserves the history.",
       @bootstrap},
      {"cqr", "refresh", "definition",
       "Staleness primitive. Maps to epistemic maintenance: re-derives freshness for an entity or a scope subtree under cost accounting.",
       @bootstrap}
    ]
  end

  defp architecture do
    [
      {"architecture", "grafeo_nif", "definition",
       "Embedded Rust graph database exposed to the BEAM via a rustler NIF. Stores nodes, edges, vectors and WAL in process.",
       @bootstrap},
      {"architecture", "beam_runtime", "definition",
       "Erlang virtual machine hosting the Elixir application. Preemptive scheduler, process isolation, supervisor trees.",
       @bootstrap},
      {"architecture", "otp_supervision", "definition",
       "One-for-one supervisor owning Grafeo.Server, ScopeTree and the MCP transport. Restarts children on crash, bounds blast radius.",
       @bootstrap},
      {"architecture", "mcp_transport", "definition",
       "stdio JSON-RPC transport exposing the seven CQR primitives as MCP tools for Claude Desktop and other MCP clients.",
       @bootstrap},
      {"architecture", "engine_boundary", "definition",
       "Cqr.Engine.execute/2 is the single governance invariance boundary. All delivery interfaces route through it.",
       @bootstrap},
      {"architecture", "scope_model", "definition",
       "Hierarchical scope tree with bidirectional visibility: ancestors for fallback, descendants for ownership, siblings hidden.",
       @bootstrap},
      {"architecture", "adapter_contract", "definition",
       "Cqr.Adapter.Behaviour defines the contract for resolve, discover, assert, certify, trace, signal, refresh across backends.",
       @bootstrap},
      {"architecture", "quality_envelope", "definition",
       "Every result carries a Cqr.Quality struct: reputation, owner, certified_by, certified_at, freshness, provenance.",
       @bootstrap},
      {"architecture", "error_semantics", "definition",
       "Cqr.Error carries code, message, retry_guidance and similar_entities. Errors are data, not exceptions.",
       @bootstrap},
      {"architecture", "multi_paradigm_query", "definition",
       "DISCOVER runs graph, BM25 and vector retrieval under one scope filter. Modalities merge by entity identity with source tags.",
       @bootstrap},
      {"architecture", "persistent_storage", "definition",
       "Single .grafeo file with sidecar WAL directory. Checkpoint on close. Bootstrap creates scope tree plus one entity on empty DB.",
       @bootstrap},
      {"architecture", "embedding_model", "definition",
       "Deterministic 384-dim bag-of-words pseudo embedding used for tests and seed data. Cosine similarity via hash collision overlap.",
       @bootstrap},
      {"architecture", "nimble_parsec", "definition",
       "Parser combinator library used to parse CQR expressions into typed ASTs. One module per primitive, shared terminals.",
       @bootstrap},
      {"architecture", "ets_scope_cache", "definition",
       "Public ETS table loaded at boot with the scope tree. Visibility queries read from ETS without a GenServer hop.",
       @bootstrap},
      {"architecture", "cost_accounting", "definition",
       "Cqr.Cost attached to every result: adapters queried, operations count, execution ms. Budgets live above the engine.",
       @bootstrap}
    ]
  end

  defp tech do
    [
      {"tech", "elixir", "definition",
       "Functional language on the BEAM. Pattern matching, pipe operator, supervised processes. Primary implementation language.",
       @bootstrap},
      {"tech", "erlang_otp", "definition",
       "Actor runtime and battle-tested standard library. Provides GenServer, Supervisor, ETS and a preemptive scheduler.",
       @bootstrap},
      {"tech", "phoenix_liveview", "definition",
       "Server-rendered UI framework over WebSockets. Candidate for a future operator dashboard on top of the CQR engine.",
       @bootstrap},
      {"tech", "rustler", "definition",
       "Safe Rust-to-Elixir NIF bridge. Encodes and decodes BEAM terms, manages resource lifetimes, schedules dirty IO.",
       @bootstrap},
      {"tech", "grafeo_database", "definition",
       "Embedded Rust graph database with GQL and Cypher. Single-file storage format with sidecar WAL and checkpoint on close.",
       @bootstrap},
      {"tech", "nimble_parsec_lib", "definition",
       "Elixir parser combinator library used to build the CQR expression parser with fast compile-time-compiled grammars.",
       @bootstrap},
      {"tech", "jason_json", "definition",
       "Elixir JSON encoder used for MCP JSON-RPC. Crashes on non-encodable terms, so tuples must be normalized to maps or lists.",
       @bootstrap},
      {"tech", "docker_compose", "definition",
       "Container orchestration for local dev stacks. Not required to run the MCP server but useful for reverse proxies and adapters.",
       @bootstrap},
      {"tech", "git_gpg", "definition",
       "GPG-signed git commits enforced on main. Authors prove identity per commit. All commits use -S.",
       @bootstrap},
      {"tech", "qwen_local_llm", "definition",
       "Local Qwen family LLM used for on-device reasoning and as a generation harness for cognitive testing of the graph.",
       @bootstrap},
      {"tech", "bsl_license", "definition",
       "Business Source License for the public code. Converts to an open license after a change date. Commercial use gated.",
       @bootstrap},
      {"tech", "github_pages", "definition",
       "Static hosting for the marketing and docs site. Jekyll-based, auto-deployed from the main branch of the docs repo.",
       @bootstrap}
    ]
  end

  defp bugs do
    [
      {"bugs", "n_plus_1_query", "observation",
       "Early adapter fetched related entities one Cypher query per node. Fixed by collapsing to a single scoped MATCH plus Elixir grouping.",
       @bootstrap},
      {"bugs", "jason_tuple_crash", "observation",
       "Jason.encode crashed on raw Elixir tuples in MCP results. Fixed by normalizing tuples to maps at the adapter boundary.",
       @bootstrap},
      {"bugs", "zombie_beam_processes", "observation",
       "Stale BEAM processes held the Grafeo file lock after exit. Fixed with pkill -9 plus sleep in restart scripts.",
       @bootstrap},
      {"bugs", "nif_preemption", "observation",
       "Long NIF calls blocked the scheduler. Fixed by marking execute as DirtyIo so the BEAM can run other processes during IO.",
       @bootstrap},
      {"bugs", "missing_embedding", "observation",
       "Asserted entities had no embedding so free-text DISCOVER never found them via the vector path. Fixed in commit 66d29f4.",
       @bootstrap},
      {"bugs", "blog_in_repo", "observation",
       "Blog draft accidentally committed to the main repo. Removed and added to .gitignore. Drafts now live outside the repo.",
       @bootstrap},
      {"bugs", "non_ascii_tools", "observation",
       "MCP tool descriptions with em-dashes and smart quotes broke Claude Desktops JSON parser. Enforced ASCII only for wire strings.",
       @bootstrap},
      {"bugs", "hardcoded_tool_count", "observation",
       "Docs hardcoded a tool count that drifted as primitives shipped. Replaced with a computed count from the capabilities list.",
       @bootstrap},
      {"bugs", "async_race_condition", "observation",
       "Parallel resolve via Task.async_stream surfaced an ordering-dependent test. Fixed by pattern matching on content, not index.",
       @bootstrap},
      {"bugs", "grafeo_extension", "observation",
       "Persistent DB path used .db extension which Grafeos auto-detect did not recognize. Fixed by switching to .grafeo extension.",
       @bootstrap},
      {"bugs", "wal_sigkill", "observation",
       "SingleFile WAL auto commit does not write TransactionCommit, so SIGKILL loses data. Sync mode helps only legacy WAL dir.",
       @bootstrap},
      {"bugs", "cosine_gap", "observation",
       "Pseudo-embedding hash collisions produce false-positive cosine hits. Tests must tolerate vector-only hits or filter by text.",
       @bootstrap}
    ]
  end

  defp strategy do
    [
      {"strategy", "protocol_stack", "definition",
       "CQR is positioned as a governance protocol layer above vector stores and graph DBs, not as a new database.",
       @bootstrap},
      {"strategy", "governance_first", "definition",
       "Retrieval quality flows from governance primitives like scope, provenance, certification, not from model scale.",
       @bootstrap},
      {"strategy", "epistemic_provenance", "definition",
       "Every result carries its derivation chain. Claims are rumor until certified. The paper trail is the product.",
       @bootstrap},
      {"strategy", "acquirer_targets", "definition",
       "Data governance vendors, RAG platforms and enterprise search players are the natural acquirers within 36 months.",
       @bootstrap},
      {"strategy", "adapter_ecosystem", "definition",
       "Adapters for Postgres, Elastic, Pinecone, Snowflake, Databricks. The CQR layer sits above existing enterprise stores.",
       @bootstrap},
      {"strategy", "licensing_model", "definition",
       "BSL for public code, commercial licenses for production use. Free for research, paid for revenue generation.",
       @bootstrap},
      {"strategy", "design_partners", "definition",
       "Three pilot customers across finance, healthcare and public sector. Each validates scope governance under real data.",
       @bootstrap},
      {"strategy", "six_month_plan", "definition",
       "Ship V1 with seven primitives, recruit two design partners, file the core patent, close a seed round by month six.",
       @bootstrap},
      {"strategy", "patent_filing", "definition",
       "Core claims cover scope-first multi-paradigm query inversion and certification-backed provenance on a federated store.",
       @bootstrap},
      {"strategy", "valuation", "definition",
       "Seed valuation anchored to the federation adapter surface and patent claims, not to revenue or user counts.",
       @bootstrap},
      {"strategy", "cqr_vs_rag", "definition",
       "RAG does similarity first and filters by access after. CQR filters by scope first and then runs retrieval. Invariant: scope.",
       @bootstrap},
      {"strategy", "market_timing", "definition",
       "Agent ecosystems need a governance substrate before enterprise adoption. CQR targets this window before big-co locks it in.",
       @bootstrap},
      {"strategy", "commercialization", "definition",
       "Open protocol, commercial adapters and governance tooling. License revenue from adapters, not from the engine.",
       @bootstrap},
      {"strategy", "advisors", "definition",
       "Advisory board weighted toward data governance, enterprise sales and patent strategy. Small, compensated in equity.",
       @bootstrap},
      {"strategy", "runway", "definition",
       "Target 18 months of runway after seed close. Hire selectively around adapter builds and design-partner integration.",
       @bootstrap}
    ]
  end

  defp metrics do
    finance = [
      {"finance", "arr", "metric",
       "Annual recurring revenue across all active subscription contracts.", @bootstrap},
      {"finance", "mrr", "metric", "Monthly recurring revenue, a leading indicator of ARR.",
       @bootstrap},
      {"finance", "burn_rate", "metric",
       "Monthly net cash outflow. Paired with runway for solvency planning.", @bootstrap},
      {"finance", "operating_expenses", "metric",
       "Total operating expenses across payroll, cloud, tooling and overhead.", @bootstrap},
      {"finance", "revenue_growth", "metric", "Quarter-over-quarter revenue growth rate.",
       @bootstrap},
      {"finance", "ltv", "metric",
       "Customer lifetime value estimated from retention and expansion curves.", @bootstrap},
      {"finance", "cac", "metric",
       "Customer acquisition cost by cohort across paid and organic channels.", @bootstrap},
      {"finance", "gross_margin", "metric",
       "Revenue minus cost of goods sold as a percentage of revenue.", @bootstrap},
      {"finance", "runway_months", "metric",
       "Cash balance divided by burn rate. Months of solvency at current spend.", @bootstrap},
      {"finance", "ebitda", "metric",
       "Earnings before interest, taxes, depreciation and amortization.", @bootstrap}
    ]

    product = [
      {"product", "dau", "metric", "Daily active users observed via product analytics.",
       @bootstrap},
      {"product", "mau", "metric", "Monthly active users aggregated from daily telemetry.",
       @bootstrap},
      {"product", "retention_rate", "metric", "30-day user retention rate by cohort.",
       @bootstrap},
      {"product", "feature_adoption", "metric",
       "Percentage of active users exercising a feature within 30 days of release.", @bootstrap},
      {"product", "time_to_value", "metric", "Median time from signup to first value event.",
       @bootstrap},
      {"product", "session_length", "metric",
       "Median session duration on the primary product surface.", @bootstrap}
    ]

    engineering = [
      {"engineering", "deployment_frequency", "metric", "Production deployments per week.",
       @bootstrap},
      {"engineering", "mttr", "metric", "Mean time to recovery from production incidents.",
       @bootstrap},
      {"engineering", "change_failure_rate", "metric",
       "Percentage of deployments causing incidents.", @bootstrap},
      {"engineering", "lead_time", "metric",
       "Lead time from commit to production for merged pull requests.", @bootstrap},
      {"engineering", "test_coverage", "metric", "Line coverage of the automated test suite.",
       @bootstrap},
      {"engineering", "incident_rate", "metric", "Production incidents per week by severity.",
       @bootstrap}
    ]

    hr = [
      {"hr", "headcount", "metric", "Total active employee headcount.", @bootstrap},
      {"hr", "attrition_rate", "metric",
       "Employee attrition rate on a rolling twelve-month basis.", @bootstrap},
      {"hr", "enps", "metric", "Employee net promoter score from the latest pulse survey.",
       @bootstrap},
      {"hr", "hiring_velocity", "metric", "Average days from job posting to signed offer.",
       @bootstrap},
      {"hr", "compensation_ratio", "metric",
       "Compensation relative to the market median for each role.", @bootstrap}
    ]

    cs = [
      {"cs", "csat", "metric", "Customer satisfaction score from ticket-close surveys.",
       @bootstrap},
      {"cs", "ticket_resolution_time", "metric",
       "Median support ticket resolution time in hours.", @bootstrap},
      {"cs", "expansion_revenue", "metric",
       "Revenue from existing-customer expansions and upsells.", @bootstrap}
    ]

    finance ++ product ++ engineering ++ hr ++ cs
  end

  defp insights do
    [
      {"insights", "ltv_cac_ratio", "derived_metric",
       "Ratio of customer lifetime value to customer acquisition cost. Healthy SaaS targets are above 3.",
       ["entity:finance:ltv", "entity:finance:cac"]},
      {"insights", "churn_arr_impact", "derived_metric",
       "Expected ARR loss from current churn rate projected over the next four quarters.",
       ["entity:product:retention_rate", "entity:finance:arr"]},
      {"insights", "attrition_velocity_lag", "observation",
       "Hiring velocity below attrition rate indicates net headcount decline. Correlates with engineering throughput loss.",
       ["entity:hr:attrition_rate", "entity:hr:hiring_velocity"]},
      {"insights", "nps_expansion_correlation", "observation",
       "Customer NPS correlates with expansion revenue six months out. High NPS precedes upsell.",
       ["entity:cs:csat", "entity:cs:expansion_revenue"]},
      {"insights", "deployment_incident_tradeoff", "observation",
       "High deployment frequency with flat change-failure rate indicates a healthy delivery pipeline.",
       ["entity:engineering:deployment_frequency", "entity:engineering:change_failure_rate"]},
      {"insights", "burn_runway_pressure", "derived_metric",
       "Runway months below twelve triggers a hiring freeze decision. Derived from burn_rate and cash balance.",
       ["entity:finance:burn_rate", "entity:finance:runway_months"]},
      {"insights", "adoption_retention_loop", "observation",
       "Feature adoption within the first seven days predicts 90-day retention. Classical onboarding signal.",
       ["entity:product:feature_adoption", "entity:product:retention_rate"]},
      {"insights", "mrr_arr_consistency", "derived_metric",
       "MRR times twelve should approximate ARR within three percent. Divergence flags contract accounting errors.",
       ["entity:finance:mrr", "entity:finance:arr"]},
      {"insights", "mttr_csat_link", "observation",
       "Longer MTTR on customer-facing incidents depresses CSAT for the following quarter.",
       ["entity:engineering:mttr", "entity:cs:csat"]},
      {"insights", "enps_attrition_leader", "observation",
       "eNPS below zero leads attrition by one to two quarters. Useful early warning for retention interventions.",
       ["entity:hr:enps", "entity:hr:attrition_rate"]},
      {"insights", "coverage_failure_correlation", "observation",
       "Test coverage above 80 percent correlates with lower change-failure rate but does not guarantee it.",
       ["entity:engineering:test_coverage", "entity:engineering:change_failure_rate"]},
      {"insights", "mau_dau_stickiness", "derived_metric",
       "DAU divided by MAU is the stickiness ratio. Values above 0.2 indicate daily-habit products.",
       ["entity:product:dau", "entity:product:mau"]}
    ]
  end

  defp roadmap do
    [
      {"roadmap", "compare", "definition",
       "Future primitive for side-by-side evaluation of alternatives under shared constraints.",
       @bootstrap},
      {"roadmap", "hypothesize", "definition",
       "Future primitive for generating candidate assertions with confidence bounds before certification.",
       @bootstrap},
      {"roadmap", "anchor", "definition",
       "Future primitive for binding an entity to an external identity like a URL or a DOI to prevent drift.",
       @bootstrap},
      {"roadmap", "awareness", "definition",
       "Future primitive exposing which adapters and entities an agent has touched in the current session.",
       @bootstrap},
      {"roadmap", "multi_agent", "definition",
       "Multi-agent coordination: agents share a scope graph while maintaining independent reputations and audit trails.",
       @bootstrap},
      {"roadmap", "agent_studio", "definition",
       "Authoring environment for assembling agents from primitives, scopes and adapter policies.",
       @bootstrap},
      {"roadmap", "sse_transport", "definition",
       "Server-sent events MCP transport for browser clients in addition to stdio. Keeps the same tool surface.",
       @bootstrap},
      {"roadmap", "enterprise_adapters", "definition",
       "First-party adapters for Snowflake, Databricks, Postgres and Elastic with scope-aware query rewriting.",
       @bootstrap},
      {"roadmap", "periodic_checkpoint", "definition",
       "Server-side periodic checkpoint calls so SingleFile Grafeo auto-commit data survives unexpected process kills.",
       @bootstrap},
      {"roadmap", "transformer_embeddings", "definition",
       "Pluggable real embedding models alongside the pseudo-embedding baseline for production workloads.",
       @bootstrap}
    ]
  end

  defp governance do
    [
      {"governance", "scope_hierarchy", "definition",
       "Ordered tree of scopes from root to leaves. Every entity belongs to at least one scope.",
       @bootstrap},
      {"governance", "genuine_invisibility", "definition",
       "A sibling scopes data is not retrievable by any query, not just filtered out in results.",
       @bootstrap},
      {"governance", "cert_lifecycle", "definition",
       "Entities transition from asserted to certified to deprecated. Each transition logs an audit record.",
       @bootstrap},
      {"governance", "trust_quantified", "definition",
       "Trust is a function of reputation, certification authority and derivation chain length.",
       @bootstrap},
      {"governance", "agent_identity", "definition",
       "Every operation carries an agent_id. Audit records, reputation updates and scope policies key on it.",
       @bootstrap},
      {"governance", "cost_budget", "definition",
       "Each agent has a cost budget for operations, adapters queried and latency. Overruns are visible to the caller.",
       @bootstrap},
      {"governance", "rumor_paper_trail", "definition",
       "An asserted claim is a rumor until certified. The paper trail is preserved regardless of certification status.",
       @bootstrap},
      {"governance", "concentric_rings", "definition",
       "Layered governance policies: personal, team, org, regulator. Outer rings override inner rings on conflict.",
       @bootstrap},
      {"governance", "clean_framework", "definition",
       "A minimal governance framework: scope, provenance, certification, signal. Nothing else is privileged.",
       @bootstrap},
      {"governance", "consecration", "definition",
       "Certification is consecration: an authority stamps the entity and the stamp is permanent in the audit trail.",
       @bootstrap},
      {"governance", "luhmann_trust", "definition",
       "Niklas Luhmanns view of trust as risk reduction under complexity. CQR operationalizes this with provenance.",
       @bootstrap},
      {"governance", "whakapapa", "definition",
       "Maori concept of genealogical lineage. Analogous to derivation chains in CQR. Every fact has a lineage.",
       @bootstrap},
      {"governance", "scope_enforcement", "definition",
       "Scope is enforced inside MATCH clauses, not as a post-filter. An out-of-scope entity is never materialized.",
       @bootstrap},
      {"governance", "audit_nodes", "definition",
       "AssertionRecord, CertificationRecord and SignalRecord nodes hold the audit trail separate from live entities.",
       @bootstrap},
      {"governance", "conflict_preservation", "definition",
       "When adapters disagree, CQR preserves all conflicting values with attribution. Resolution is a policy decision.",
       @bootstrap}
    ]
  end

  defp lessons do
    [
      {"lessons", "hire_when_hurts", "observation",
       "Only hire for roles where the absence is causing pain today. Pre-emptive hiring burns runway and dilutes focus.",
       @bootstrap},
      {"lessons", "speed_not_rush", "observation",
       "Ship fast by cutting scope, not by cutting tests. Rushed code without tests becomes its own drag within a week.",
       @bootstrap},
      {"lessons", "relational_first", "observation",
       "Model the entity graph before the storage layer. Schema follows from the relationships, not the other way around.",
       @bootstrap},
      {"lessons", "prompt_chunks", "observation",
       "Break large prompts into composable chunks with explicit handoffs. Long single prompts drift context.",
       @bootstrap},
      {"lessons", "tests_and_docs", "observation",
       "Tests guard behavior. Docs guard intent. Neither is optional on a shipping primitive.",
       @bootstrap},
      {"lessons", "zombie_prevention", "observation",
       "Always pkill -9 plus sleep 2 before restarting the MCP server. Zombie BEAMs hold the Grafeo file lock and corrupt state.",
       @bootstrap},
      {"lessons", "root_cause_first", "observation",
       "Do not paper over failures with catch-alls. Root cause first, even if it means reverting and redoing.",
       @bootstrap},
      {"lessons", "agnostic_patents", "observation",
       "Patent claims should be storage and vendor agnostic. Specific implementations weaken defensibility.",
       @bootstrap},
      {"lessons", "commercialization_gap", "observation",
       "Great primitives do not sell themselves. Commercial adapters and integration stories close the gap to revenue.",
       @bootstrap},
      {"lessons", "worktree_required", "observation",
       "Parallel Claude Code sessions on the same repo need git worktrees. Shared checkout causes merge conflicts and lost work.",
       @bootstrap},
      {"lessons", "nif_no_preempt", "observation",
       "Long NIF calls must be marked DirtyIo or DirtyCpu. Otherwise the BEAM scheduler blocks and everything else stalls.",
       @bootstrap},
      {"lessons", "normalize_for_jason", "observation",
       "Normalize tuples and atoms to maps and strings before handing results to Jason. Jason crashes on raw Erlang terms.",
       @bootstrap},
      {"lessons", "grafeo_extension", "observation",
       "The .grafeo file extension is load-bearing. Grafeos auto-detect picks SingleFile only when it sees .grafeo.",
       @bootstrap},
      {"lessons", "sigterm_first", "observation",
       "Send SIGTERM and wait for graceful shutdown before SIGKILL. Grafeo only persists on graceful close.",
       @bootstrap},
      {"lessons", "scope_ordering", "observation",
       "Visible-scopes ordering matters: self first, then ancestors, then descendants. The adapter uses head-of-list for defaults.",
       @bootstrap}
    ]
  end

  defp org do
    [
      {"org", "teipsum", "definition",
       "Company name. Latin for yourself. Domain acquired early. Brand ties to identity and self-governance.",
       @bootstrap},
      {"org", "unica_platform", "definition",
       "Parent platform positioning CQR as the governance layer beneath a broader cognitive software stack.",
       @bootstrap},
      {"org", "founder_background", "definition",
       "Founder with enterprise engineering leadership experience at Walmart and EPAM and a Marine Corps officer background.",
       @bootstrap},
      {"org", "hardware", "definition",
       "Primary dev box is an Apple Silicon Mac with local LLM inference. Secondary Linux machines for CI and long runs.",
       @bootstrap},
      {"org", "dev_stack", "definition",
       "Elixir, Rust, Grafeo, Claude Code as a coding copilot, local Qwen for offline reasoning, GitHub for hosting.",
       @bootstrap},
      {"org", "walmart_governance", "definition",
       "Prior work at Walmart on governance and data platforms informs CQRs scope-first invariants.",
       @bootstrap},
      {"org", "epam_role", "definition",
       "Principal engineer experience at EPAM across enterprise accounts sharpens integration and adapter instincts.",
       @bootstrap},
      {"org", "marine_corps", "definition",
       "Prior service shaped operational discipline, chain-of-command thinking and a bias toward field-tested solutions.",
       @bootstrap},
      {"org", "matias_reyes", "definition",
       "Principal technical collaborator. Deep Elixir and Erlang expertise. Code reviewer and design partner.",
       @bootstrap},
      {"org", "alejandro_advisor", "definition",
       "Advisor with enterprise sales background. Helps sequence the design-partner pipeline and early contracts.",
       @bootstrap},
      {"org", "octavio_network", "definition",
       "Chilean tech network contact who opens doors to LatAm design partners and local talent.",
       @bootstrap},
      {"org", "workiva_runway", "definition",
       "Prior Workiva equity provides personal runway through seed. Reduces pressure to raise prematurely on bad terms.",
       @bootstrap},
      {"org", "deployment_verticals", "definition",
       "Initial target verticals: financial services, regulated healthcare, public sector. Governance-heavy data environments.",
       @bootstrap},
      {"org", "chile_base", "definition",
       "Operating from Chile with US incorporation. Favorable engineering talent pool and time-zone overlap with US East.",
       @bootstrap},
      {"org", "domain_history", "definition",
       "Domain portfolio accumulated over a decade around identity, governance and epistemic software themes.",
       @bootstrap}
    ]
  end

  defp scenarios do
    [
      {"scenario", "analyst_onboarding", "recommendation",
       "New analyst onboards by RESOLVEing core metrics, DISCOVERing related concepts and TRACEing provenance of key assertions.",
       @bootstrap},
      {"scenario", "churn_investigation", "recommendation",
       "Start with retention_rate, DISCOVER related product signals, TRACE cert history, SIGNAL reputation drops on stale metrics.",
       @bootstrap},
      {"scenario", "budget_planning", "recommendation",
       "RESOLVE finance metrics, DISCOVER cross-domain insights, ASSERT scenarios with DERIVED_FROM chains for each plan variant.",
       @bootstrap},
      {"scenario", "incident_response", "recommendation",
       "DISCOVER engineering incident metrics, TRACE deployment history, SIGNAL reputation on entities involved in the incident.",
       @bootstrap},
      {"scenario", "talent_crisis", "recommendation",
       "RESOLVE headcount and attrition, TRACE eNPS history, DISCOVER compensation signals, CERTIFY an action plan by HR lead.",
       @bootstrap},
      {"scenario", "governance_audit", "recommendation",
       "TRACE every certified entity in a scope for the last quarter. Flag entities with short derivation chains for re-certification.",
       @bootstrap},
      {"scenario", "cross_domain", "recommendation",
       "DISCOVER entities across finance and product scopes with a root agent. Merge modalities by entity identity, rank by combined score.",
       @bootstrap},
      {"scenario", "trust_evaluation", "recommendation",
       "For each result, inspect quality envelope: reputation, certified_by, certified_at. Prefer certified entities with recent timestamps.",
       @bootstrap},
      {"scenario", "knowledge_curation", "recommendation",
       "Scheduled REFRESH over a scope subtree. Entities past the staleness threshold get a freshness signal and a retry guidance.",
       @bootstrap},
      {"scenario", "competitive_analysis", "recommendation",
       "ASSERT competitor entities with DERIVED_FROM market-research sources. CERTIFY by strategy lead. TRACE for pricing changes.",
       @bootstrap},
      {"scenario", "agent_collaboration", "recommendation",
       "Two agents share a scope. Each asserts entities independently. Conflicts are preserved. Certification resolves the canonical view.",
       @bootstrap},
      {"scenario", "pipeline_failure", "recommendation",
       "DISCOVER engineering entities related to pipeline. RESOLVE each failure record. TRACE the deployment lineage. SIGNAL reputation.",
       @bootstrap},
      {"scenario", "board_preparation", "recommendation",
       "RESOLVE top-level finance metrics. DISCOVER associated insights. Attach quality envelopes to the board deck for auditability.",
       @bootstrap},
      {"scenario", "product_launch", "recommendation",
       "ASSERT launch entity with DERIVED_FROM feature entities. CERTIFY by product lead. SIGNAL adoption telemetry post-launch.",
       @bootstrap},
      {"scenario", "compliance_check", "recommendation",
       "TRACE all entities in a regulated scope. Verify each has a certified_by and certified_at within the required recency window.",
       @bootstrap},
      {"scenario", "succession_planning", "recommendation",
       "RESOLVE role entities. DISCOVER candidate entities by scope. ASSERT succession plan entities with DERIVED_FROM evaluation records.",
       @bootstrap},
      {"scenario", "metric_deprecation", "recommendation",
       "SIGNAL reputation drop to zero on an obsolete metric. CERTIFY a replacement. TRACE captures the deprecation event end-to-end.",
       @bootstrap},
      {"scenario", "multi_model_validation", "recommendation",
       "Query multiple embedding adapters. Conflicts in vector similarity are preserved per-adapter for downstream resolution.",
       @bootstrap},
      {"scenario", "adapter_integration", "recommendation",
       "New adapter is introduced via the behaviour contract. Existing primitives require no code changes. Scope is enforced by the engine.",
       @bootstrap},
      {"scenario", "semantic_drift", "recommendation",
       "REFRESH staleness on all scope entities monthly. Stale entities trigger a SIGNAL plus a suggestion to re-certify or deprecate.",
       @bootstrap}
    ]
  end
end
